### ISSUE TITLE
GeoIP Enricher

### ISSUE THREAD

**Issue by ST2Labs** [wizzie-io/enricher#15]
Hi,

I'm testing GeoIPEnricher, and I would like to know if database (*.dat) is update .. because I have diference between geoip plugin in logstash vs GeoIPEnrich

Thanks in Advace.
Great works !

**Comment by andresgomezfrr** [comment]
Hi @ST2Labs,

Currently, we are using the Maxmind GeoIP v1. I check on the Maxmind repo, and I see that Maxmind GeoIP v2 is ready to use. 

http://maxmind.github.io/GeoIP2-java/

So, the database (*.dat) is outdated. 

We are going to work on that. However, if you want to make a pull request, we will be delighted.
